name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # or replace with your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the version that works with your project

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Export static files
        run: npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './out'  # This is the default directory Next.js exports to
